language: python
python:
    - "2.6"
    - "2.7"
    - "3.3"
    - "3.4"
services:
    - mongodb
    - rabbitmq
    - redis-server
#addons:
    #postgresql: "9.4"
before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -y beanstalkd
    - echo "START=yes" | sudo tee -a /etc/default/beanstalkd > /dev/null
    - sudo service beanstalkd start
install:
    - pip install --allow-all-external -r requirements.txt
    - pip install coveralls httpbin pyproxy>=0.1.6
    - if [[ $TRAVIS_PYTHON_VERSION == 2* ]]; then travis_retry pip install beanstalkc; fi
    - pip install -e .
script:
    - coverage run setup.py test
after_success:
    - coverage combine
    - coveralls
